version : "3.6"

volumes:
  auth-database-dev:
    name: ${DC_VOLUME}-dev

  auth-api-dev:
    name: ${DC_API_NAME}-dev

services:
  database:
    container_name: ${DC_CONTAINER_NAME}-dev
    volumes:
      - auth-database-dev:/var/lib/cassandra
    ports:
      - ${DB_PORT_DEV}:9042
    networks:
      - auth-api-network

  api:
    container_name: ${DC_API_NAME}-dev
    image: ${DC_API_NAME}-dev-image:dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    ports:
      - 6000:5000
    networks:
      - auth-api-network